# Dockerfile for project

# inherit from python image
FROM ghcr.io/napari/napari-xpra:sha-010f1e1

# update to latest pip version 
RUN pip uninstall opencv-python
RUN pip install opencv-python-headless
RUN pip install simpleitk

RUN pip install torch torchvision hydra-core iopath

WORKDIR /app

COPY ./napari-interactive /app/napari-interactive
RUN pip install -e /app/napari-interactive
COPY ./napari-interactive /app/napari-interactive
RUN pip install -e /app/napari-interactive
COPY ./napari-shifted-labels /app/napari-shifted-labels
RUN pip install -e /app/napari-shifted-labels
COPY ./napari-edit-log /app/napari-edit-log
RUN pip install -e /app/napari-edit-log

COPY ./installation/start_web.sh /app/start_web.sh

ENTRYPOINT [ "/bin/bash", "start_web.sh" ]